### ISSUE TITLE
Support for Dunfell

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/meta-kanto#47]
Dunfell has [Long Term Support](https://wiki.yoctoproject.org/wiki/Releases) and it'll improve the project adoption. In the same way as it was implemented for Kirkstone, we need a new branch (called dunfell) where all recipes will be adopted. Note that the adoption will require a bunch of updates because Kirstone introduced some language changes:
- [Release notes for 4.0 (kirkstone)](https://docs.yoctoproject.org/migration-guides/release-notes-4.0.html)
- [Migration notes for 4.0 (kirkstone)](https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html#migration-notes-for-4-0-kirkstone)

**Comment by hristobojilov** [comment]
After short discussion we have decided that we cannot support this old yocto version.
