### ISSUE TITLE
Kanto Container Management recipe fails to compile for Leda-Distro (kirkstone) 

### ISSUE THREAD

**Issue by vasilvas99** [eclipse-kanto/meta-kanto#51]
## Issue description
The Container Management recipe uses ${AUTOREV} thus pulling the latest commit from container-management. This now fails to compile for Leda-Distro which is based on kirkstone. 

The full recipe log can be found here: 
[kanto_cm_compile_failure.log](https://github.com/eclipse-kanto/meta-kanto/files/11260341/kanto_cm_compile_failure.log)

The lines containing the failure:
```text
HASH subkey 7ebe85e22f308a2556eb2dce4f9d611c371d0064f995533f6a3ed8738e9bf1ee "stdout" = 67c71b5ad3badf4147a7ac7cfaa2eacf4017d1f060a8b3dae9415254e28cfcc1
# github.com/docker/docker/libnetwork/networkdb
../../../../pkg/mod/github.com/moby/moby@v23.0.3+incompatible/libnetwork/networkdb/networkdb.go:149:16: undefined: atomic.Int64
../../../../pkg/mod/github.com/moby/moby@v23.0.3+incompatible/libnetwork/networkdb/networkdb.go:154:16: undefined: atomic.Int64
HASH subkey f8474e3cf420c317c9d2d8bcc1224e1d7bf857bcc9d01cdbb952715199e5dd60 "link-stdout" = d096858d49809339f49411b2867f7ff73433ab348a826577d56fd45a24739b1c
WARNING: exit code 2 from a shell command.
```
The issue seems to be connected to bump in the moby version: https://github.com/eclipse-kanto/container-management/pull/146

## Workaround for Leda
In `meta-leda` we have opted for our 0.1.0-M1-release to use a fixed [known-good commit hash for CM](https://github.com/eclipse-leda/meta-leda/blob/main/meta-leda-components/recipes-sdv/eclipse-kanto/container-management_%25.bbappend#L24).

## Steps to reproduce:
1. Checkout https://github.com/eclipse-leda/leda-distro (branch 0.1.0-M1)
2. Following the leda-documentation setup an environment where you can [build Leda 0.1.0-M1 with kas](https://eclipse-leda.github.io/leda/docs/build/devenv/build-kas-manually/).
3. Run `kas checkout kas/leda-qemux86-64.yaml`
4. Comment out in `meta-leda/meta-leda-components/recipes-sdv/eclipse-kanto/container-management_%.bbappend` the `L24: SRCREV="65e00358fa5aed1792059488a80fe755b36a8191"`
5. Run: `kas shell kas/leda-qemux86-64.yaml -c 'bitbake container-management'` (to only run the CM recipe) or `kas build kas/leda-qemux86-64.yaml` (to run a full Leda-distro build)

**Comment by hristobojilov** [comment]
Can you build with newer Yocto version like langdale?

**Comment by vasilvas99** [comment]
Hi, we would like to support Kirkstone as it's the LTS version of Yocto (until ~April 2024), and Langdale is EOL on 1 May 2023.
From what I have managed to gathered, the issue is that Moby 23.0.3 uses the `atomic.Int64` which were introduced in Golang version 1.9 and Poky kirkstone provides go 1.7, correct?

**Comment by k-gostev** [comment]
This should be mitigated with [#57]. Since there is not much else to do I am closing the issue.

**Comment by mikehaller** [comment]
You may have a look at [Yocto Documentation - LTS Mixin](https://wiki.yoctoproject.org/wiki/Stable_Release_and_LTS#LTS_.E2.80.9CMixin.E2.80.9D_repositories) or [meta-lts-mixins](https://git.yoctoproject.org/meta-lts-mixins)

It may be exactly what you need to use a newer version of GoLang and still continue to support current LTS release versions of Yocto.

For example, there is [GoLang 1.20.5 as of 2023-06-21](https://git.yoctoproject.org/meta-lts-mixins/commit/?h=kirkstone/go&id=315d2d288fdcd2768f189101d980f40b0f2c9b0d)
