### ISSUE TITLE
Yocto recipe for Kanto AWS Connector

### ISSUE THREAD

**Issue by k-gostev** [eclipse-kanto/meta-kanto#75]
The recipe should be able to:

- build Kanto AWS Connector from sources
- integrate the related resources: service file, configuration, certificates etc.
- support various platforms/architectures

**Comment by AhmedElkazzaz** [comment]
I am trying to use this connector ,but can't connect to AWS.
it shows:
settings validation error: device ID 'AWS IoT Certificate' has invalid namespace ID.

Please ,Can you help me with using this connector ?
