### ISSUE TITLE
Unable to run the container docker image with kirkstone

### ISSUE THREAD

**Issue by Mahesha-M** [eclipse-kanto/meta-kanto#87]
Hello Everyone,

We have integrated the below mentioned meta-kanto kirkstone branch components to one of our IoT product with all the dependencies requested.
1. suite-connector
2. mosquitto
3. aws-connector
4. azure-connector
5. **container-management**
6. update-manager
7. software-update
8. system-metrics

We can able to create container images but unable to run those.

Here are the logs for more insight.
**1. Installed Kernel modules:**
root@xxxxxxxx:~# lsmod
Module                      Size  Used by
xt_conntrack              16384  1
xt_MASQUERADE      16384  2
nf_conntrack_netlink 45056  0
nfnetlink                    20480  2 nf_conntrack_netlink
iptable_nat                16384  1
nf_nat                        45056  2 iptable_nat,xt_MASQUERADE
nf_conntrack             139264  4 xt_conntrack,nf_nat,nf_conntrack_netlink,xt_MASQUERADE
nf_defrag_ipv6          24576  1 nf_conntrack
nf_defrag_ipv4          16384  1 nf_conntrack
libcrc32c                   16384  2 nf_conntrack,nf_nat
xt_addrtype              16384  3
iptable_filter             16384  1
ip_tables                   32768  2 iptable_filter,iptable_nat
x_tables                    45056  6 xt_conntrack,iptable_filter,xt_addrtype,ip_tables,iptable_nat,xt_MASQUERADE
br_netfilter               32768  0
algif_hash                 20480  1
algif_skcipher           20480  1
af_alg                        32768  6 algif_hash,algif_skcipher
overlay                     122880  1
brcmfmac                 303104  0
brcmutil                   20480  1 brcmfmac
cfg80211                  405504  1 brcmfmac
compat                    16384  2 brcmfmac,cfg80211
imx_sdma                 32768  2
fuse                          131072  1

**2. containerd service status**
root@xxxxxxx:~# systemctl status containerd.service
* containerd.service - containerd container runtime
     Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-05-15 10:01:58 UTC; 1h 11min ago
       Docs: https://containerd.io/
   Main PID: 398 (containerd)
      Tasks: 11
     Memory: 65.3M
     CGroup: /system.slice/containerd.service
             `-398 /usr/bin/containerd
 
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.790239062Z" level=info msg="Start subscribing containerd event"
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.812236458Z" level=info msg="Start recovering state"
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.815632567Z" level=info msg="Start event monitor"
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.816473063Z" level=info msg="Start snapshots syncer"
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.817204435Z" level=info msg="Start cni network conf syncer for default"
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.818282680Z" level=info msg="Start streaming server"
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.792727176Z" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.824756149Z" level=info msg=serving... address=/run/containerd/containerd.sock
May 15 10:01:58 imx8mmphantom systemd[1]: Started containerd container runtime.
May 15 10:01:58 imx8mmphantom containerd[398]: time="2024-05-15T10:01:58.841313945Z" level=info msg="containerd successfully booted in 1.110983s"
Hint: Some lines were ellipsized, use -l to show in full.

**3. container-management service status**
root@xxxxxxxx:~# systemctl status container-management.service
* container-management.service - Eclipse Kanto - Container Management
     Loaded: loaded (/lib/systemd/system/container-management.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-05-15 10:55:01 UTC; 18min ago
       Docs: https://eclipse.org/kanto/docs/
   Main PID: 23423 (container-manag)
      Tasks: 8 (limit: 1609)
     Memory: 27.0M
     CGroup: /system.slice/container-management.service
             `-23423 /usr/bin/container-management --cfg-file /etc/container-management/config.json
 
May 15 10:55:01 imx8mmphantom systemd[1]: Started Eclipse Kanto - Container Management.
May 15 10:55:02 imx8mmphantom container-management[23423]: time="2024-05-15T10:55:02Z" level=info msg="[container-management][daemon_config_util....ig.json]"
May 15 10:55:03 imx8mmphantom container-management[23423]: subscribed for  edge/thing/response
May 15 10:55:03 imx8mmphantom container-management[23423]: Topic: edge/thing/response
May 15 10:55:03 imx8mmphantom container-management[23423]: Message: {"deviceId":"uat6kor:kantotest1","tenantId":"integration"}
May 15 10:55:03 imx8mmphantom container-management[23423]: notified for client initialization successfully
Hint: Some lines were ellipsized, use -l to show in full.

**4. container-management log**
[container-management.log](https://github.com/eclipse-kanto/meta-kanto/files/15344226/container-management.log)

**Comment by Mahesha-M** [comment]
Hello everyone!!!!
I've finally found the root cause of the issue and it is resolved after adding all the kernel modules which container management dependent on it in kirkstone yocto version.

This issue is due to missing multiple kernel modules in default kirkstone configuration which we need to find and enable in order to successfully initialize the container management and execute kanto-cm commands on container images.

All the issues I've faced and the corresponding solutions what I've applied is listing down below.
**1. container management build issue**: 
**Detailed issue:** Kirkstone has go version 1.17.x. but container management module requires go 1.19.7 and later version.
**Solution:** Added go 1.19.7 version under meta-bsp recipes-devtools and added PREFERRED_VERSION_go=1.19.7 in image configuration.

**2. container management Initialization issue:**
**Detailed issue:** Container management was not initialized properly due to missing number of kernel modules.
**Solution:** Added/enabled below listed kernel modules.
-  CONFIG_NAMESPACES=y
- CONFIG_UTS_NS=y
- CONFIG_IPC_NS=y
- CONFIG_USER_NS=y
- CONFIG_PID_NS=y
- CONFIG_NET_NS=y

**3. Unable to execute kanto-cm start/stop command on container images:**
**Detailed issue:**
**Solution:** Added/enabled below listed kernel modules.
- CONFIG_VETH=y
- CONFIG_NET_KEY=y
- CONFIG_XFRM_USER=y
- CONFIG_XFRM_ALGO=y
- CONFIG_INET_AH=y
- CONFIG_INET_ESP=y
- CONFIG_INET_IPCOMP=y
- CONFIG_INET_XFRM_TUNNEL=y


After making all the changes mentioned above, now I'm able to run the container images.
![Uploading image.png…]()

**Comment by k-gostev** [comment]
I would be good to mention that this issue was happening on [i.MX 8M](https://www.nxp.com/design/design-center/development-boards-and-designs/i-mx-evaluation-and-development-boards/evaluation-kit-for-the-i-mx-8m-mini-applications-processor:8MMINILPD4-EVK) device.
Thanks @Mahesha-M, this would be quite helpful for everyone who is building Kanto for NXP boards.

**Comment by Mahesha-M** [comment]
Same issue is faced while integrating Meta-Kanto Kirkstone branch for RaspberryPi 4 board as well. I would recommend taking these changes in Meta-Kanto Kirkstone branch.

**Comment by jetm** [comment]
I had the same issue with a TI board using the `linux-staging-ti` kernel from the `meta-ti` layer.

List of kernel modules to be added in order to make `kcm-kanto` work:
```
CONFIG_BRIDGE_VLAN_FILTERING=y
CONFIG_CGROUP_BPF=y
CONFIG_DM_THIN_PROVISIONING=m
CONFIG_INET_AH=y
CONFIG_INET_ESP=y
CONFIG_INET_IPCOMP=y
CONFIG_INET_XFRM_TUNNEL=y
CONFIG_IPC_NS=y
CONFIG_IPVLAN=m
CONFIG_IP_NF_FILTER=m
CONFIG_IP_NF_NAT=m
CONFIG_IP_NF_TARGET_MASQUERADE=m
CONFIG_NAMESPACES=y
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=m
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NETFILTER_XT_MATCH_IPVS=m
CONFIG_NET_KEY=y
CONFIG_NET_NS=y
CONFIG_NF_CONNTRACK=y
CONFIG_NF_NAT=m
CONFIG_OVERLAY_FS=y
CONFIG_PID_NS=y
CONFIG_USER_NS=y
CONFIG_UTS_NS=y
CONFIG_VETH=y
CONFIG_VLAN_8021Q=y
CONFIG_XFRM_ALGO=y
CONFIG_XFRM_USER=y
```
